apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  containers:
  - env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: INTERNAL
    - name: KAFKA_LISTENERS
      value: INTERNAL://:29092,EXTERNAL://:9092
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    - name: KAFKA_RESTART_ATTEMPTS
      value: "10"
    - name: KAFKA_RESTART_DELAY
      value: "5"
    - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
      value: "6000"
    - name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
      value: "0"
    image: obsidiandynamics/kafka
    name: kafka
    ports:
    - containerPort: 2181
    - containerPort: 9092
    resources: {}
  restartPolicy: Never
status: {}
